/** GF × SSB meeting pre-read — agenda, Traceability Pack questions, label checklist */

export const GREEN_FUTURE_MEETING_PACK_SUBJECT =
  "Pre-read: GF × SSB Meeting Pack — Label, Test Order, Traceability (Ref. GF/SSB/2026-0821)";

export const GREEN_FUTURE_MEETING_PACK_RAW = `Subject: Pre-read: GF × SSB Meeting Pack — Label, Test Order, Traceability (Ref. GF/SSB/2026-0821)

Green Future × Smile Seed Bank — 60-minute meeting pack
Ref. GF/SSB/2026-0821 · Internal / partner pre-read

---

A) Meeting agenda (60 minutes)

| Block | Time | Topic | Target outcome |
| --- | --- | --- | --- |
| 1 | 0–5 min | Confirm alignment on GF/SSB/2026-0821 | No open disputes on framework |
| 2 | 5–20 min | Label template — legal fields first | Mandatory DOA field list agreed; GF working template received; approval workflow + print gate defined |
| 3 | 20–35 min | First test order quotation | Strains, quantities, pack format, COA option, EUR/THB price, 50% advance, balance due, indicative ship date |
| 4 | 35–45 min | Quality acceptance + claims | 80/99 spec in PO; GF Claims Procedure Template received; SSB storage log capability confirmed |
| 5 | 45–55 min | Traceability Pack (design only) | Field ownership, immutability, access method, brand/GACP photo rules — launch after test order |
| 6 | 55–60 min | Next steps | GF sends quotation + label template; SSB issues PO; schedule Distribution Agreement draft |

---

B) Traceability Pack — discussion questions

Data fields

1. Which fields are generated by Smile Seed Bank vs copied verbatim from Green Future lot data?
2. Confirm the immutable GF fields: Variety Code, Lot/Batch No., Germination, Purity, Test Date, Test Basis, Source Document / Version — any additions?
3. Will lot data be delivered as signed PDF (prevails) plus CSV for import — confirm template version on each delivery?

Access and security

4. Preferred access model: authenticated farm customer account, QR token per lot, or both?
5. Should extended information (beyond public lot summary) require login only — no public search by lot number?
6. Audit log requirements: who changed what, when — retention period?

Brand and content

7. PDF must state it is not a GACP certificate and does not guarantee certification — confirm exact disclaimer text.
8. May Smile Seed Bank include Green Future variety code + commercial name only — no pedigree, no facility photos without written approval?
9. If facility photographs are ever included, separate written approval per image — confirm process.

Implementation

10. Smile Seed Bank will submit PDF template mock-up for GF written approval before any customer-facing launch.
11. Target: design locked at this meeting; development and launch after first test order delivery and lot data import validated.

---

C) Legal-first label checklist (before commercial branding)

Mandatory on every sealed unit (confirm with DOA + mutual written approval)

| # | Field | Source | Example / note |
| --- | --- | --- | --- |
| 1 | Licensed seller legal name | SSB | T.M.Y Agro Trade Limited Partnership |
| 2 | Por.Por. 4 licence number | SSB | 1011043900042568 |
| 3 | Licensed premises / address | SSB | As on Por.Por. 4 |
| 4 | Lot / batch number | GF | e.g. GF-AF99-2608-B01 |
| 5 | Variety code | GF | e.g. AF99 |
| 6 | Commercial product name | GF + approved | e.g. BUBBA KUSH AUTO |
| 7 | Pack size (seed count) | Order | e.g. 50 seeds |
| 8 | Germination % | GF lot data | Per test for this lot |
| 9 | Purity % | GF lot data | Per test for this lot |
| 10 | Test date | GF lot data | |
| 11 | Additional DOA mandatory fields | Legal review | Confirm with GF template + DOA |

Workflow gates

- Gate 1: Legal label approved in writing by both parties — no print before this.
- Gate 2: Commercial branding (Smile Seed Bank / co-brand artwork) approved separately — applied only after Gate 1.
- Gate 3: Version number + approval date on label appendix — any change requires re-approval.

Printing responsibility

- Green Future prints lot labels, applies, fills, seals, dispatches — Smile Seed Bank does not repack or relabel.

Storage reminder (post-delivery, SSB)

- +5 to +10 °C stable; RH 45–50%, not exceeding 50%; original sealed packaging; separate lot storage; acclimatise before opening cold pack; electronic temp/RH log for claims.

---

Prepared by Smile Seed Bank / T.M.Y Agro Trade Limited Partnership
Ref. GF/SSB/2026-0821
`;
